code/SocialGames.Web/Areas/Samples/Controllers/ClientTestController.cs
namespace Microsoft.Samples.SocialGames.Web.Areas.Samples.Controllers
{
    using System.Web.Mvc;

    public class ClientTestController : Controller
    {
        public ActionResult TicTacToeGameTest()
        {
            return View();
        }

        public ActionResult TicTacToeBoardTest()
        {
            return View();
        }

        public ActionResult FourInARowGameTest()
        {
            return View();
        }

        public ActionResult FourInARowBoardTest()
        {
            return View();
        }
    }
}

code/SocialGames.Web/Areas/Samples/Controllers/FourInARowController.cs
namespace Microsoft.Samples.SocialGames.Web.Areas.Samples.Controllers
{
    using System.Web.Mvc;
    using Microsoft.Samples.SocialGames.Web.Controllers;

    public class FourInARowController : BaseController
    {
        [Authorize]
        public ActionResult Index()
        {
            return View();
        }
    }
}

code/SocialGames.Web/Areas/Samples/Controllers/TicTacToeController.cs
namespace Microsoft.Samples.SocialGames.Web.Areas.Samples.Controllers
{
    using System.Web.Mvc;
    using Microsoft.Samples.SocialGames.Web.Controllers;

    public class TicTacToeController : BaseController
    {
        [Authorize]
        public ActionResult Index()
        {
            return View();
        }
    }
}

code/SocialGames.Web/Controllers/AccountController.cs
namespace Microsoft.Samples.SocialGames.Web.Controllers
{
    using System;
    using System.Linq;
    using System.Threading;
    using System.Web.Mvc;
    using Microsoft.IdentityModel.Claims;
    using Microsoft.IdentityModel.Protocols.WSFederation;
    using Microsoft.Samples.SocialGames;
    using Microsoft.Samples.SocialGames.Entities;
    using Microsoft.Samples.SocialGames.Repositories;
    using Microsoft.Samples.SocialGames.Web.Services;

    public class AccountController : BaseController
    {
        private readonly IUserRepository userRepository;
        private IUserProvider userProvider;

        public AccountController(IUserRepository userRepository, IUserProvider userProvider)
        {
            this.userRepository = userRepository;
            this.userProvider = userProvider;
        }

        public ActionResult LogOn(string returnUrl)
        {
            return View();
        }
       
        [HttpPost]
        public ActionResult LogOn()
        {
            if (this.Request.IsAuthenticated)
            {
                // Ensure user profile
                var userId = this.GetClaimValue(ClaimTypes.NameIdentifier);
                var userProfile = this.userRepository.GetUser(userId);
                if (userProfile == null)
                {
                    var loginType = this.GetClaimValue(ConfigurationConstants.IdentityProviderClaimType);
                    userProfile = new UserProfile
                    {
                        Id = userId,
                        DisplayName = Thread.CurrentPrincipal.Identity.Name ?? string.Empty,
                        LoginType = loginType,
                        AssociatedUserAccount = 
                            loginType.StartsWith("Facebook", StringComparison.OrdinalIgnoreCase) ? 
                                this.GetClaimValue(ConfigurationConstants.FacebookAccessTokenClaimType) :
                                string.Empty
                    };

                    this.userRepository.AddOrUpdateUser(userProfile);
                }
                
                var effectiveReturnUrl = this.GetContextFromRequest();

                if (!string.IsNullOrWhiteSpace(effectiveReturnUrl))
                {
                    return Redirect(effectiveReturnUrl);
                }
            }

            return Redirect("~/");
        }

        [Authorize]
        public ActionResult Friends(string id)
        {
            if (!string.IsNullOrEmpty(id))
            {
                string currentUserId = this.userProvider.UserId;
                string inviteUserId = id;

                this.userRepository.AddFriend(currentUserId, inviteUserId);
                this.userRepository.AddFriend(inviteUserId, currentUserId);
                return RedirectToAction("Index", "Home");
            }

            this.ViewBag.CurrentUserId = this.userProvider.UserId;
            return View();
        }

        [Authorize]
        public ActionResult Profile()
        {
            this.ViewBag.CurrentUserId = this.userProvider.UserId;
            return View();
        }

        [Authorize]
        public ActionResult Leaderboard()
        {
            this.ViewBag.CurrentUserId = this.userProvider.UserId;
            return View();
        }

        private string GetContextFromRequest()
        {
            Uri requestBaseUrl = WSFederationMessage.GetBaseUrl(this.Request.Url);
            var message = WSFederationMessage.CreateFromNameValueCollection(requestBaseUrl, this.Request.Form);
            
            return message != null ? message.Context : string.Empty;
        }

        private string GetClaimValue(string claimType)
        {
            if (!Thread.CurrentPrincipal.Identity.IsAuthenticated)
            {
                throw new InvalidOperationException("User is not authenticated");
            }

            var claimsIdentity = (IClaimsIdentity)Thread.CurrentPrincipal.Identity;

            if (!claimsIdentity.Claims.Any(c => c.ClaimType.Equals(claimType, StringComparison.OrdinalIgnoreCase)))
            {
                throw new InvalidOperationException("Claim not found: " + claimType);
            }

            return claimsIdentity.Claims.FirstOrDefault(c => c.ClaimType.Equals(claimType, StringComparison.OrdinalIgnoreCase)).Value;
        }
    }
}

code/SocialGames.Web/Controllers/BaseController.cs
namespace Microsoft.Samples.SocialGames.Web.Controllers
{
    using System.Web.Mvc;

    public class BaseController : Controller
    {
        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            this.ViewBag.BlobUrl = System.Configuration.ConfigurationManager.AppSettings["BlobUrl"];
            this.ViewBag.ApiUrl = System.Configuration.ConfigurationManager.AppSettings["ApiUrl"];

            base.OnActionExecuting(filterContext);
        }
    }
}

code/SocialGames.Web/Controllers/HomeController.cs
namespace Microsoft.Samples.SocialGames.Web.Controllers
{
    using System.Web.Mvc;

    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

code/SocialGames.Web/Controllers/TestController.cs
namespace Microsoft.Samples.SocialGames.Controllers
{
    using System.Web.Mvc;
    using Microsoft.Samples.SocialGames.Web.Controllers;

    public class TestController : BaseController
    {
        public ActionResult Index()
        {
            return View();
        }

        [Authorize]
        public ActionResult ServerInterfaceTest()
        {
            return View();
        }

        [Authorize]
        public ActionResult GameServiceTest()
        {
            return View();
        }

        [Authorize]
        public ActionResult UserServiceTest()
        {
            return View();
        }
    }
}

code/SocialGames.Web/Areas/Samples/Views/FourInARow/Index.cshtml
@{
    ViewBag.Title = "Four in a Row";
}

<script src="@Url.Content("~/Scripts/jQuery.tmpl.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/knockout-1.2.1.js")" type="text/javascript"></script>

<script src="@Url.Content("~/Scripts/Games/ServerInterface.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/Games/GameService.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/Games/UserService.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/Games/FourInARow/Board.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/Games/FourInARow/Game.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/Games/FourInARow/ViewModel.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/Games/FourInARow/Controller.js")" type="text/javascript"></script>

<h2>Four in a Row</h2>

<div id="game">
    <div style="display: none" data-bind="visible: gameQueueId() != null">
        <fieldset>
            <legend>Player</legend>
            <div>
                Welcome <b><span data-bind='text: playerName()'></span></b>
            </div>
            <div data-bind="visible: isOwner() && gameQueueId() != null && gameId() == null">
                <span>Use this URL to invite other players: <span data-bind="text: inviteURL()" />
                </span>
                <br />
                <div data-bind="visible: friends() != null && friends().length > 0">
                Your Friends
                <select id="friends" data-bind="options: friends, optionsValue: 'Id', optionsText: 'DisplayName'">
                </select>
                    <a href="#" data-bind="click: inviteFriend">Invite Friend</a>
                </div>
            </div>
            <br />
            <div data-bind="visible: noPlayers() == 1 && isOwner()">
                <span>Waiting for your opponent...</span>
            </div>
        </fieldset>
    </div>
    <div style="display: none" data-bind="visible: gameQueueId() != null">
        <fieldset>
            <legend>Players</legend>
            <div data-bind='template: { name: "queueStatus", foreach: players()}' />
            <script id="queueStatus" type="text/html">
            <li><b>${$data.UserName}</b></li>
            </script>
        </fieldset>
    </div>
    <div style="display: none" data-bind="visible: gameId() != null">
        <fieldset>
            <legend>Game</legend>
            <div>
                You are <span data-bind="visible: playerColor() == C4Color.Cross">Xs</span> <span
                    data-bind="visible: playerColor() == C4Color.Circle">Os</span>
            </div>
            <div data-bind="visible: playerColor() == currentColor()">
                Your turn!</div>
            <div data-bind="visible: playerColor() != currentColor()">
                Opponent turn!</div>
            <div data-bind="visible: isTie()">
                Tie!!</div>
            <div data-bind="visible: playerColor() == winnerColor()">
                You won!!</div>
            <div data-bind="visible: playerColor() != winnerColor() && winnerColor() != C4Color.Empty">
                You lose!!</div>
            <canvas id="board" width="600" height="600"></canvas>
        </fieldset>
    </div>
</div>
<div id="notSupported" style="display:none">
    <h3>Sorry, your browser is too old. It does not support HTML5 canvas.</h3>
    <p>You can download <a href="http://www.microsoft.com/download/en/default.aspx">IE9</a></p>
</div>

<script type="text/javascript">
    var viewModel;
    var gameQueueId = getQueryVariable("id");
    var nullGameId = "00000000-0000-0000-0000-000000000000";

    function getQueryVariable(variable) {
        var query = window.location.search.substring(1);
        var vars = query.split("&");

        for (var i = 0; i < vars.length; i++) {
            var pair = vars[i].split("=");
            if (pair[0] == variable) {
                return pair[1];
            }
        }
    }

    var apiURL = "@this.ViewBag.ApiUrl";
    var blobURL = "@this.ViewBag.BlobUrl";

    var si = new ServerInterface();
    var gs = new GameService(apiURL, blobURL, si);
    var us = new UserService(apiURL, blobURL, si);

    var controller;

    function inviteFriend() {
        var userId = $("#friends").val();
        var userName = $("#friends :selected").text();
        gs.inviteUser(viewModel.gameQueueId(), userId, "Invitation for Four in a Row", viewModel.inviteURL(), function () { alert(userName + " was invited") });
    }

    function sgusersCallback(user) {
        if (user.DisplayName != null && user.DisplayName != "")
            viewModel.playerName(user.DisplayName);
        else
            viewModel.playerName(user.Id);
    }

    function start(userId) {
        // check for canvas, show an "Upgrade your browser" screen if they don't have it.
        var canvas = document.getElementById('board');
        if (canvas.getContext == null || canvas.getContext('2d') == null) {
            $("#game").toggle();
            $("#notSupported").toggle();

            return;
        }
        
        var board = new FourInARowBoard(canvas, 6, 6);
        var game = new FourInARowGame(6, 6);

        var controller = new FourInARowController(viewModel, gs, board, game);

        controller.setGameQueueId(gameQueueId);

        controller.start();

        us.getFriendsInfo(function (friends) { viewModel.friends(friends); });
        us.getUser(userId, function () { });
    }

    $(function () {
        viewModel = new FourInARowViewModel();
        ko.applyBindings(viewModel);

        us.verify(
            function (userId) { start(userId); },
            function () {
                var newlocation = '@Url.Action("LogOn", "Account", new { Area = "", ReturnUrl = "replace-in-js" })';
                newlocation = newlocation.replace("replace-in-js", encodeURIComponent(window.location.href));
                window.location.assign(newlocation);
            }
        );
    });
</script>

code/SocialGames.Web/Areas/Samples/Views/TicTacToe/Index.cshtml
@{
    ViewBag.Title = "Tic Tac Toe";
}

<script src="@Url.Content("~/Scripts/jQuery.tmpl.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/knockout-1.2.1.js")" type="text/javascript"></script>

<script src="@Url.Content("~/Scripts/Games/ServerInterface.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/Games/GameService.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/Games/UserService.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/Games/TicTacToe/Board.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/Games/TicTacToe/Game.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/Games/TicTacToe/ViewModel.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/Games/TicTacToe/Controller.js")" type="text/javascript"></script>

<h2>Tic Tac Toe</h2>
<div id="game">
    <div style="display: none" data-bind="visible: gameQueueId() != null">
        <fieldset>
            <legend>Player</legend>
            <div>
                Welcome <b><span data-bind='text: playerName()'></span></b>
            </div>
            <div data-bind="visible: isOwner() && gameQueueId() != null && gameId() == null">
                <span>Use this URL to invite other players: <span data-bind="text: inviteURL()" />
                </span>
                <br />
                <div data-bind="visible: friends() != null && friends().length > 0">
                Your Friends
                <select id="friends" data-bind="options: friends, optionsValue: 'Id', optionsText: 'DisplayName'">
                </select>
                    <a href="#" data-bind="click: inviteFriend">Invite Friend</a>
                </div>
            </div>
            <br />
            <div data-bind="visible: noPlayers() == 1 && isOwner()">
                <span>Waiting for your opponent...</span>
            </div>
        </fieldset>
    </div>
    <div style="display: none" data-bind="visible: gameQueueId() != null">
        <fieldset>
            <legend>Players</legend>
            <div data-bind='template: { name: "queueStatus", foreach: players()}' />
            <script id="queueStatus" type="text/html">
            <li><b>${$data.UserName}</b></li>
            </script>
        </fieldset>
    </div>
    <div style="display: none" data-bind="visible: gameId() != null">
        <fieldset>
            <legend>Game</legend>
            <div>
                You are <span data-bind="visible: playerColor() == TTTColor.Cross">Xs</span> <span
                    data-bind="visible: playerColor() == TTTColor.Circle">Os</span>
            </div>
            <div data-bind="visible: playerColor() == currentColor()">
                Your turn!</div>
            <div data-bind="visible: playerColor() != currentColor()">
                Opponent turn!</div>
            <div data-bind="visible: isTie()">
                Tie!!</div>
            <div data-bind="visible: playerColor() == winnerColor()">
                You won!!</div>
            <div data-bind="visible: playerColor() != winnerColor() && winnerColor() != TTTColor.Empty">
                You lose!!</div>
            <canvas id="board" width="300" height="300"></canvas>
        </fieldset>
    </div>
</div>
<div id="notSupported" style="display:none">
    <h3>Sorry, your browser is too old. It does not support HTML5 canvas.</h3>
    <p>You can download <a href="http://www.microsoft.com/download/en/default.aspx">IE9</a></p>
</div>

<script type="text/javascript">
    var viewModel;
    var gameQueueId = getQueryVariable("id");
    var nullGameId = "00000000-0000-0000-0000-000000000000";

    function getQueryVariable(variable) {
        var query = window.location.search.substring(1);
        var vars = query.split("&");

        for (var i = 0; i < vars.length; i++) {
            var pair = vars[i].split("=");
            if (pair[0] == variable) {
                return pair[1];
            }
        }
    }

    var apiURL = "@this.ViewBag.ApiUrl";
    var blobURL = "@this.ViewBag.BlobUrl";

    var si = new ServerInterface();
    var gs = new GameService(apiURL, blobURL, si);
    var user = new UserService(apiURL, blobURL, si);

    var controller;

    function inviteFriend() {
        var userId = $("#friends").val();
        var userName = $("#friends :selected").text();
        gs.inviteUser(viewModel.gameQueueId(), userId, "Invitation for Tic Tac Toe", viewModel.inviteURL(), function () { alert(userName + " was invited") });
    }

    function sgusersCallback(user) {
        if (user.DisplayName != null && user.DisplayName != "")
            viewModel.playerName(user.DisplayName);
        else
            viewModel.playerName(user.Id);
    }

    function start(userId) {

        // check for canvas, show an "Upgrade your browser" screen if they don't have it.
        var canvas = document.getElementById('board');
        if (canvas.getContext == null || canvas.getContext('2d') == null) {
            $("#game").toggle();
            $("#notSupported").toggle();

            return;
        }

        var board = new TicTacToeBoard(canvas);
        var game = new TicTacToeGame();

        var controller = new TicTacToeController(viewModel, gs, board, game);

        controller.setGameQueueId(gameQueueId);

        controller.start();

        user.getFriendsInfo(function (friends) { viewModel.friends(friends); });
        user.getUser(userId, function () { });
    }

    $(function () {
        viewModel = new TicTacToeViewModel();
        ko.applyBindings(viewModel);

        user.verify(
            function (userId) { start(userId); },
            function () {
                var newlocation = '@Url.Action("LogOn", "Account", new { Area = "", ReturnUrl = "replace-in-js" })';
                newlocation = newlocation.replace("replace-in-js", encodeURIComponent(window.location.href));
                window.location.assign(newlocation);
            }
        );
    });
</script>

code/SocialGames.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Home</h2>

<p>
This site showcases two sample games that consumes the operations exposed by a generic game play service API. The game play service is responsible for handling the generic game operations like user authentication, joining multiple players to a game, and persisting the game live state. 
</p>

@if (Request.IsAuthenticated)
{
<p>
    Select an option from the menu to start playing with the samples, see your profile and friends, and check your score on the leaderboard!
</p>
}
else
{
<p>
    Click @Html.ActionLink("Log On", "LogOn", "Account") to authenticate.
</p>
}

code/SocialGames.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.7.1.js")" type="text/javascript"></script>
</head>
<body>
    <div class="page">
        <header>
            <div id="title">
                <h1>Social Gaming Examples</h1>
            </div>
            <div id="logindisplay">
                &nbsp;
            </div>
            <div style="clear:both;"></div>

            <nav>
                <ul id="menu">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Tic Tac Toe", "Index", "TicTacToe", new { area = "Samples" }, null)</li>
                    <li>@Html.ActionLink("Four in a Row", "Index", "FourInARow", new { area = "Samples" }, null)</li>
                    <li>@Html.ActionLink("Tests", "Index", "Test", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Friends", "Friends", "Account", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Profile", "Profile", "Account", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Leaderboard", "Leaderboard", "Account", new { area = "" }, null)</li>
                </ul>
            </nav>
        </header>
        <section id="main">
            @RenderBody()
        </section>
        <footer>
        </footer>
    </div>
</body></html>

code/SocialGames.Web/Views/Shared/_LogOnPartial.cshtml
@if(Request.IsAuthenticated) {
    <text>Welcome <strong>@User.Identity.Name</strong>!
    [ @Html.ActionLink("Log Off", "LogOff", "Account") ]</text>
}
else {
    @:[ @Html.ActionLink("Log On", "LogOn", "Account") ]
}

code/SocialGames.Web/Views/Test/GameServiceTest.cshtml
@{
    ViewBag.Title = "GameService Test";
}

<link href="@Url.Content("~/Content/qunit.css")" rel="stylesheet" type="text/css" />
<script src="@Url.Content("~/Scripts/qunit.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/Games/ServerInterface.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/Games/GameService.js")" type="text/javascript"></script>


<h1 id="qunit-header">GameService Tests</h1>

<h2 id="qunit-banner"></h2>
<div id="qunit-testrunner-toolbar"></div>
<h2 id="qunit-userAgent"></h2>
<ol id="qunit-tests"></ol>
<div id="qunit-fixture">test markup, will be hidden</div>

<script type="text/javascript">
    var nullGameId = "00000000-0000-0000-0000-000000000000";
    
    function testQueueCallback(data) {
        ok(true);
        start();
    }

    $(function () {
        var apiURL = "@this.ViewBag.ApiUrl";
        var blobURL = "@this.ViewBag.BlobUrl";

        var si = new ServerInterface();
        var gs = new GameService(apiURL, blobURL, si);
        gs.queueCallback = testQueueCallback;

        test("Create Game Queue", function () {
            var success = function (result) { ok(true); start(); };
            stop(10000);
            expect(1);
            gs.createGameQueue(success);
        });

        test("Join Game Queue", function () {
            var success = function (result) { ok(true); start(); };
            stop(10000);
            expect(1);

            function join(result) {
                gs.joinGameQueue(result, success);
            };

            gs.createGameQueue(join);
        });

        test("Get Game Queue", function () {
            var success = function (result) { ok(true); start(); };
            stop(10000);
            expect(1);

            function getQueue(queueId) {
                gs.getGameQueueStatus(queueId, success);
            };

            gs.createGameQueue(getQueue);
        });

        test("Start Game", function () {
            var success = function (result) { ok(true); start(); };
            stop(10000);
            expect(1);
            var queueId;

            function join(data) {
                queueId = data;
                gs.joinGameQueue(queueId, startGame);
            };

            function startGame(data) {
                gs.startGame(queueId, success);
            };

            gs.createGameQueue(join);
        });

        test("Post Statistics Event", function () {
            var success = function (result) { ok(true); start(); };
            stop(10000);
            expect(1);
            var action = { type: 1, commandData: { Victories: 0, Defeats: 0, GameCount: 0} };

            gs.postStatisticsEvent(action, success);
        });
    });
</script>

code/SocialGames.Web/Views/Test/Index.cshtml
@{
    ViewBag.Title = "Tests";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Tests</h2>

<h3>Game Support</h3>
                <ul>
                    <li>@Html.ActionLink("Server Interface", "ServerInterfaceTest", "Test")</li>
                    <li>@Html.ActionLink("Game Service", "GameServiceTest", "Test")</li>
                    <li>@Html.ActionLink("User Service", "UserServiceTest", "Test")</li>
                </ul>

<h3>Tic Tac Toe</h3>
                <ul>
                    <li>@Html.ActionLink("Game Logic", "TicTacToeGameTest", "ClientTest", new { area = "Samples" }, null)</li>
                    <li>@Html.ActionLink("Board", "TicTacToeBoardTest", "ClientTest", new { area = "Samples" }, null)</li>
                </ul>
<h3>Four in a Row</h3>
                <ul>
                    <li>@Html.ActionLink("Game Logic", "FourInARowGameTest", "ClientTest", new { area = "Samples" }, null)</li>
                    <li>@Html.ActionLink("Board", "FourInARowBoardTest", "ClientTest", new { area = "Samples" }, null)</li>
                </ul>

code/SocialGames.Web/Views/Test/ServerInterfaceTest.cshtml
@{
    ViewBag.Title = "ServerInterface Test";
}

<link href="@Url.Content("~/Content/qunit.css")" rel="stylesheet" type="text/css" />
<script src="@Url.Content("~/Scripts/qunit.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/Games/ServerInterface.js")" type="text/javascript"></script>


<h1 id="qunit-header">ServerInterface Tests</h1>

<h2 id="qunit-banner"></h2>
<div id="qunit-testrunner-toolbar"></div>
<h2 id="qunit-userAgent"></h2>
<ol id="qunit-tests"></ol>
<div id="qunit-fixture">test markup, will be hidden</div>

<script type="text/javascript">

    function sggamesqueuesCallback(data) {
        ok(true);
        start();
    }

    $(function () {
        var apiURL = "@this.ViewBag.ApiUrl";
        var blobURL = "@this.ViewBag.BlobUrl";

        var si = new ServerInterface();

        function ajaxGetError(req, status, error) {
            start();
            si.onAjaxGetError(req, status, error);
        }

        function ajaxPostError(req, status, error) {
            start();
            si.onAjaxPostError(req, status, error);
        }

        test("Call User/Verify", function () {
            var success = function (result) { ok(true); start(); };
            var error = ajaxGetError;
            stop(10000);
            expect(1);
            si.sendAjaxGet(apiURL + "user/verify", success);
        });

        test("Create Game Queue", function () {
            var si = new ServerInterface();

            var success = function (result) { ok(true); start(); };
            stop(10000);
            expect(1);
            si.sendAjaxPost(apiURL + "game/create", { gameType: "invitation" }, success, ajaxPostError);
        });

        test("Create and Get Game Queue", function () {
            var si = new ServerInterface();

            stop(10000);
            expect(2);
            si.sendAjaxPost(apiURL + "game/create", { gameType: "invitation" },
                function (result) {
                    ok(true);
                    si.sendAjaxJsonpGet(blobURL + "sggamesqueues/" + result+ "?callback=?", "sggamesqueuesCallback", ajaxGetError);
                }
            );
        });
    });
</script>

code/SocialGames.Web/Views/Test/UserServiceTest.cshtml
@{
    ViewBag.Title = "UserService Test";
}

<link href="@Url.Content("~/Content/qunit.css")" rel="stylesheet" type="text/css" />
<script src="@Url.Content("~/Scripts/qunit.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/Games/ServerInterface.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/Games/UserService.js")" type="text/javascript"></script>


<h1 id="qunit-header">UserService Tests</h1>

<h2 id="qunit-banner"></h2>
<div id="qunit-testrunner-toolbar"></div>
<h2 id="qunit-userAgent"></h2>
<ol id="qunit-tests"></ol>
<div id="qunit-fixture">test markup, will be hidden</div>

<script type="text/javascript">

    function sgusersCallback(data) {
        ok(true);
        start();
    }

    $(function () {
        var apiURL = "@this.ViewBag.ApiUrl";
        var blobURL = "@this.ViewBag.BlobUrl";

        var si = new ServerInterface();
        var us = new UserService(apiURL, blobURL, si);

        test("User Verify", function () {
            var success = function (result) { ok(true); start(); };
            stop(10000);
            expect(1);
            us.verify(success);
        });

        test("Get User", function () {
            var success = function (result) { ok(true); start(); };
            stop(10000);
            expect(1);

            us.verify(function(userId) {
                us.getUser(userId, success)});
        });

        test("Add Friend", function () {
            var success = function (result) { ok(true); start(); };
            stop(10000);
            expect(1);

            us.verify(function (userId) {
                us.addFriend("newFriend", success);
            });
        });

        test("Get Friends", function () {
            var success = function (result) { ok(true); start(); };
            stop(10000);
            expect(1);

            us.verify(function (userId) {
                us.getFriends(success);
            });
        });

        test("Get Friends Info", function () {
            var success = function (result) { ok(true); start(); };
            stop(10000);
            expect(1);

            us.verify(function (userId) {
                us.getFriendsInfo(success);
            });
        });

        test("Get Leaderboard", function () {
            var success = function (result) { ok(true); start(); };
            stop(10000);
            expect(1);

            us.getLeaderboard(10, success);
        });

        test("Get Leaderboard (with user focus)", function () {
            var success = function (result) { ok(true); start(); };
            stop(10000);
            expect(1);

            us.verify(function (userId) {
                us.getLeaderboardWithFocus(5, userId, success);
            });
        });
    });
</script>